export const participationModes = [
  { value: "hands-on", label: "Make or take part" },
  { value: "watch-listen", label: "Watch & listen" },
  { value: "at-table", label: "Eat & drink" },
  { value: "outdoors", label: "Be outdoors" },
  { value: "slow-down", label: "Slow down" },
] as const;
export const timeFits = [
  { value: "short", label: "A short visit" },
  { value: "half-day", label: "A morning or afternoon" },
  { value: "full-day", label: "Most of the day" },
  { value: "own-pace", label: "At my own pace" },
  { value: "calendar", label: "Let the calendar decide" },
  { value: "overnight", label: "Stay the night" },
] as const;
type Mode = (typeof participationModes)[number]["value"];
type TimeFit = (typeof timeFits)[number]["value"];
export type DiscoveryProfile = {
  modes: Mode[];
  time?: TimeFit;
  keywords: string[];
};

/** Editorial planning lenses, based on the scope and duration stated in each guide.
 * These are not live session lengths, availability or suitability guarantees. */
export const discoveryProfiles: Record<string, DiscoveryProfile> = {
  "read-the-ring-before-the-horse-runs": {
    modes: ["watch-listen", "outdoors"],
    time: "half-day",
    keywords: [
      "Sinj",
      "Croatia",
      "Alka",
      "horse",
      "museum",
      "tournament",
      "heritage",
      "ring",
      "Cetinska Krajina",
    ],
  },
  "let-the-pony-read-the-mountain": {
    modes: ["hands-on", "outdoors", "slow-down"],
    time: "half-day",
    keywords: [
      "Semonkong",
      "Lesotho",
      "Basotho pony",
      "horse riding",
      "Maletsunyane",
      "mountain",
      "guide",
      "waterfall",
    ],
  },
  "wait-until-the-turtle-is-ready": {
    modes: ["watch-listen", "outdoors", "slow-down"],
    time: "calendar",
    keywords: [
      "Tortuguero",
      "Costa Rica",
      "turtle",
      "nesting",
      "wildlife",
      "night",
      "conservation",
      "beach",
      "guide",
    ],
  },
  "read-nubia-before-the-sail-opens": {
    modes: ["watch-listen", "outdoors", "slow-down"],
    time: "half-day",
    keywords: [
      "Aswan",
      "Egypt",
      "Nubia",
      "Nubian Museum",
      "felucca",
      "Nile",
      "sailing",
      "museum",
      "river",
    ],
  },
  "watch-one-bolt-cross-the-republic": {
    modes: ["watch-listen"],
    time: "calendar",
    keywords: [
      "San Marino",
      "crossbow",
      "Cava dei Balestrieri",
      "tournament",
      "historic centre",
      "festival",
      "spectator",
    ],
  },
  "meet-the-rose-before-it-becomes-water": {
    modes: ["hands-on", "watch-listen", "outdoors"],
    time: "calendar",
    keywords: [
      "Jabal Akhdar",
      "Oman",
      "rose",
      "rosewater",
      "harvest",
      "distillation",
      "farm",
      "spring",
      "Damask rose",
    ],
  },
  "walk-inside-the-earthen-ring": {
    modes: ["watch-listen", "outdoors", "slow-down"],
    time: "half-day",
    keywords: [
      "Yongding",
      "Fujian",
      "China",
      "tulou",
      "Zhencheng Lou",
      "Hongkeng",
      "architecture",
      "heritage",
      "communal building",
    ],
  },
  "follow-the-pearl-back-underwater": {
    modes: ["outdoors", "watch-listen"],
    time: "half-day",
    keywords: [
      "Muharraq",
      "Bahrain",
      "pearl",
      "pearling",
      "snorkelling",
      "diving",
      "oyster",
      "sea",
      "boat",
    ],
  },
  "read-a-city-from-the-waterline": {
    modes: ["outdoors", "watch-listen", "slow-down"],
    time: "half-day",
    keywords: [
      "Kampong Ayer",
      "Bandar Seri Begawan",
      "Brunei",
      "water village",
      "water taxi",
      "walking",
      "stilt houses",
      "river",
    ],
  },
  "let-the-delta-decide-the-route": {
    modes: ["outdoors", "slow-down", "watch-listen"],
    time: "half-day",
    keywords: [
      "Okavango Delta",
      "Botswana",
      "mokoro",
      "canoe",
      "poler",
      "wetland",
      "wildlife",
      "water",
      "nature",
    ],
  },
  "follow-a-sheet-back-to-the-mulberry-branch": {
    modes: ["watch-listen"],
    time: "half-day",
    keywords: [
      "Konigil",
      "Samarkand",
      "Uzbekistan",
      "Meros",
      "paper mill",
      "Samarkand paper",
      "mulberry",
      "bark",
      "papermaking",
      "manuscript",
      "craft",
      "factory visit",
    ],
  },
  "follow-kente-one-strip-at-a-time": {
    modes: ["hands-on", "watch-listen"],
    time: "short",
    keywords: [
      "Bonwire",
      "Kumasi",
      "Ashanti Region",
      "Ghana",
      "kente",
      "weaving",
      "loom",
      "textile",
      "pattern",
      "thread",
      "warping",
      "master weaver",
    ],
  },
  "see-lunch-built-from-fire-stone-and-leaves": {
    modes: ["watch-listen", "at-table"],
    time: "half-day",
    keywords: [
      "Apia",
      "Samoa",
      "Upolu",
      "umu",
      "earth oven",
      "stone oven",
      "Samoa Cultural Village",
      "Samoan food",
      "lunch",
      "volcanic rocks",
      "Fa'a Samoa",
    ],
  },
  "take-the-lagoon-one-stroke-at-a-time": {
    modes: ["hands-on", "outdoors"],
    time: "half-day",
    keywords: [
      "Moorea",
      "French Polynesia",
      "Tahiti",
      "va'a",
      "vaa",
      "outrigger canoe",
      "canoe",
      "paddling",
      "lagoon",
      "We Do Va'a",
      "beginner",
    ],
  },
  "let-the-city-take-its-evening-walk": {
    modes: ["outdoors", "slow-down"],
    time: "own-pace",
    keywords: [
      "Tirana",
      "Albania",
      "xhiro",
      "evening walk",
      "promenade",
      "Grand Park",
      "lake",
      "Embassy Row",
      "public space",
    ],
  },
  "watch-a-town-move-in-prayer": {
    modes: ["watch-listen"],
    time: "calendar",
    keywords: [
      "Echternach",
      "Luxembourg",
      "hopping procession",
      "dancing procession",
      "Whit Tuesday",
      "Saint Willibrord",
      "pilgrimage",
      "UNESCO",
      "religious procession",
    ],
  },
  "let-the-leaves-reach-the-water-first": {
    modes: ["slow-down"],
    time: "short",
    keywords: [
      "Hanoi",
      "Vietnam",
      "Red Dao",
      "Dao Do",
      "herbal bath",
      "leaves",
      "wellness",
      "spa",
      "Tả Phìn",
      "Ta Phin",
    ],
  },
  "watch-flowers-enter-the-paper": {
    modes: ["watch-listen"],
    time: "short",
    keywords: [
      "Ambalavao",
      "Madagascar",
      "Antemoro",
      "Antaimoro",
      "paper",
      "flowers",
      "fibre",
      "craft",
      "workshop",
      "RN7",
    ],
  },
  "taste-the-distance-from-pod-to-bar": {
    modes: ["at-table", "watch-listen"],
    time: "short",
    keywords: [
      "São Tomé",
      "Sao Tome",
      "Príncipe",
      "Principe",
      "cacao",
      "cocoa",
      "chocolate",
      "bean to bar",
      "factory",
      "tasting",
      "roça",
      "plantation",
    ],
  },
  "meet-the-rose-before-the-perfume": {
    modes: ["hands-on", "watch-listen", "outdoors"],
    time: "calendar",
    keywords: [
      "Kazanlak",
      "Bulgaria",
      "Rose Valley",
      "rose picking",
      "rose harvest",
      "rose oil",
      "distillation",
      "festival",
      "flowers",
    ],
  },
  "let-the-shadows-move-after-angkor": {
    modes: ["watch-listen", "at-table"],
    time: "calendar",
    keywords: [
      "Siem Reap",
      "Cambodia",
      "Sbek Thom",
      "shadow puppets",
      "Reamker",
      "pin peat",
      "theatre",
      "performance",
      "after dark",
    ],
  },
  "hear-a-landscape-without-instruments": {
    modes: ["watch-listen", "slow-down"],
    time: "own-pace",
    keywords: [
      "Serpa",
      "Alentejo",
      "Portugal",
      "Cante Alentejano",
      "choir",
      "singing",
      "music",
      "museum",
      "performance",
    ],
  },
  "learn-hong-kong-one-hand-at-a-time": {
    modes: ["hands-on", "watch-listen"],
    time: "short",
    keywords: [
      "Hong Kong",
      "Central",
      "PMQ",
      "mahjong",
      "Cantonese mahjong",
      "tiles",
      "game",
      "play",
      "class",
    ],
  },
  "draw-with-silver-in-skopjes-old-bazaar": {
    modes: ["hands-on"],
    time: "full-day",
    keywords: [
      "Skopje",
      "North Macedonia",
      "Old Bazaar",
      "filigree",
      "silver",
      "jewellery",
      "jewelry",
      "wire",
      "craft",
      "workshop",
    ],
  },
  "read-a-ship-before-the-sails-arrive": {
    modes: ["watch-listen", "outdoors"],
    time: "own-pace",
    keywords: [
      "Bulukumba",
      "Bonto Bahari",
      "South Sulawesi",
      "Indonesia",
      "pinisi",
      "phinisi",
      "shipbuilding",
      "boatbuilding",
      "timber",
      "shipyard",
    ],
  },
  "follow-medellins-flowers-back-to-the-farm": {
    modes: ["watch-listen", "outdoors"],
    time: "half-day",
    keywords: [
      "Medellín",
      "Medellin",
      "Colombia",
      "Santa Elena",
      "silletero",
      "flowers",
      "farm",
      "garden",
      "parade",
      "craft",
    ],
  },
  "read-a-hive-from-the-inside": {
    modes: ["watch-listen", "slow-down"],
    time: "short",
    keywords: [
      "Slovenia",
      "Višnja Gora",
      "Visnja Gora",
      "Carniolan bee",
      "bees",
      "hive",
      "honeycomb",
      "museum",
      "beekeeping",
    ],
  },
  "follow-mastiha-back-to-the-tree": {
    modes: ["watch-listen", "outdoors"],
    time: "short",
    keywords: [
      "Greece",
      "Chios",
      "mastiha",
      "mastic",
      "resin",
      "tree",
      "Mastichochoria",
      "museum",
      "food",
      "landscape",
    ],
  },
  "make-halloumi-before-it-reaches-the-plate": {
    modes: ["hands-on", "at-table"],
    time: "full-day",
    keywords: [
      "Cyprus",
      "Troodos",
      "halloumi",
      "cheese",
      "curd",
      "anari",
      "food",
      "village",
      "workshop",
    ],
  },
  "read-a-smoke-sauna-before-the-heat": {
    modes: ["watch-listen", "slow-down"],
    time: "short",
    keywords: [
      "Estonia",
      "Võrumaa",
      "Voromaa",
      "Mooska",
      "smoke sauna",
      "timber",
      "fire",
      "heritage",
      "farm",
    ],
  },
  "fold-a-pattern-into-the-blue": {
    modes: ["hands-on"],
    time: "short",
    keywords: [
      "El Salvador",
      "Suchitoto",
      "indigo",
      "añil",
      "anil",
      "textile",
      "dye",
      "resist",
      "workshop",
    ],
  },
  "make-the-bagel-before-new-york-serves-it": {
    modes: ["hands-on", "at-table"],
    time: "short",
    keywords: [
      "New York City",
      "United States",
      "bagel",
      "bread",
      "baking",
      "boiling",
      "food",
      "class",
      "workshop",
    ],
  },
  "follow-the-fizz-through-a-working-factory": {
    modes: ["watch-listen", "at-table"],
    time: "short",
    keywords: [
      "New York City",
      "Brooklyn",
      "Cypress Hills",
      "seltzer",
      "soda",
      "egg cream",
      "factory",
      "machinery",
      "museum",
      "industry",
    ],
  },
  "open-the-other-side-of-ellis-island": {
    modes: ["watch-listen"],
    time: "half-day",
    keywords: [
      "New York City",
      "Ellis Island",
      "hospital",
      "immigration",
      "JR",
      "Unframed",
      "architecture",
      "history",
      "preservation",
      "ferry",
    ],
  },
  "make-pasta-until-the-sauce-makes-sense": {
    modes: ["hands-on", "at-table"],
    time: "half-day",
    keywords: [
      "Rome",
      "Italy",
      "pasta",
      "pastificio",
      "fettuccine",
      "ravioli",
      "tortellini",
      "cooking",
      "food",
      "workshop",
    ],
  },
  "ride-the-road-rome-built-to-leave-it": {
    modes: ["outdoors"],
    time: "half-day",
    keywords: [
      "Rome",
      "Italy",
      "Via Appia",
      "Appian Way",
      "bicycle",
      "cycling",
      "road",
      "archaeology",
      "outdoors",
      "UNESCO",
    ],
  },
  "put-the-gods-back-among-the-machines": {
    modes: ["watch-listen", "slow-down"],
    time: "short",
    keywords: [
      "Rome",
      "Italy",
      "Centrale Montemartini",
      "power station",
      "industrial",
      "machines",
      "sculpture",
      "museum",
      "archaeology",
      "Via Ostiense",
    ],
  },
  "ask-the-market-where-london-came-from": {
    modes: ["at-table", "watch-listen"],
    time: "half-day",
    keywords: [
      "London",
      "United Kingdom",
      "Borough Market",
      "market",
      "food",
      "tasting",
      "traders",
      "ingredients",
      "tour",
    ],
  },
  "meet-the-work-before-the-curtain-rises": {
    modes: ["watch-listen"],
    time: "short",
    keywords: [
      "London",
      "United Kingdom",
      "Covent Garden",
      "Royal Opera House",
      "ballet",
      "opera",
      "costume",
      "rehearsal",
      "production",
      "backstage",
    ],
  },
  "open-a-door-the-underground-left-behind": {
    modes: ["watch-listen"],
    time: "short",
    keywords: [
      "London",
      "United Kingdom",
      "Underground",
      "Tube",
      "Piccadilly Circus",
      "Hidden London",
      "transport",
      "engineering",
      "architecture",
      "history",
    ],
  },
  "make-the-morning-before-it-reaches-the-cafe": {
    modes: ["hands-on", "at-table"],
    time: "half-day",
    keywords: [
      "Paris",
      "France",
      "croissant",
      "pain au chocolat",
      "brioche",
      "bakery",
      "pastry",
      "breakfast",
      "Le Cordon Bleu",
      "workshop",
    ],
  },
  "watch-a-picture-grow-one-thread-at-a-time": {
    modes: ["watch-listen"],
    time: "short",
    keywords: [
      "Paris",
      "France",
      "Gobelins",
      "tapestry",
      "weaving",
      "loom",
      "textile",
      "craft",
      "art",
      "workshop",
    ],
  },
  "see-what-keeps-paris-moving-underground": {
    modes: ["watch-listen", "slow-down"],
    time: "short",
    keywords: [
      "Paris",
      "France",
      "sewers",
      "underground",
      "infrastructure",
      "engineering",
      "water",
      "museum",
      "work",
      "Pont de l'Alma",
    ],
  },
  "twist-the-city-before-you-taste-it": {
    modes: ["hands-on", "at-table"],
    time: "short",
    keywords: [
      "Kraków",
      "Krakow",
      "Poland",
      "obwarzanek",
      "bread",
      "baking",
      "dough",
      "food",
      "museum",
      "workshop",
    ],
  },
  "take-the-window-back-to-the-workbench": {
    modes: ["hands-on", "watch-listen"],
    time: "half-day",
    keywords: [
      "Kraków",
      "Krakow",
      "Poland",
      "stained glass",
      "glass",
      "copper",
      "soldering",
      "Wyspiański",
      "craft",
      "workshop",
    ],
  },
  "watch-a-city-arrive-in-miniature": {
    modes: ["watch-listen", "outdoors"],
    time: "calendar",
    keywords: [
      "Kraków",
      "Krakow",
      "Poland",
      "szopka",
      "nativity",
      "miniature",
      "architecture",
      "competition",
      "December",
      "UNESCO",
    ],
  },
  "meet-the-bay-on-its-working-hours": {
    modes: ["watch-listen", "at-table", "outdoors"],
    time: "half-day",
    keywords: [
      "Arcachon",
      "Cap Ferret",
      "Gujan-Mestras",
      "oysters",
      "oyster farming",
      "boat",
      "tide",
      "pescatourisme",
      "seafood",
    ],
  },
  "read-the-landscape-one-grain-at-a-time": {
    modes: ["outdoors", "slow-down"],
    time: "own-pace",
    keywords: [
      "Arcachon",
      "Dune du Pilat",
      "Pyla",
      "La Teste-de-Buch",
      "sand",
      "dune",
      "Atlantic",
      "landscape",
      "walking",
    ],
  },
  "make-something-from-the-broken-pieces": {
    modes: ["hands-on"],
    time: "half-day",
    keywords: [
      "Barcelona",
      "mosaic",
      "trencadís",
      "Gaudí",
      "ceramic",
      "Mosaiccos",
      "workshop",
      "design",
    ],
  },
  "watch-the-work-before-the-performance": {
    modes: ["watch-listen"],
    time: "short",
    keywords: [
      "Vienna",
      "Spanish Riding School",
      "Hofburg",
      "Lipizzaner",
      "horses",
      "training",
      "Morning Exercise",
    ],
  },
  "hear-the-church-before-you-climb": {
    modes: ["watch-listen", "slow-down"],
    time: "short",
    keywords: [
      "Porto",
      "Clérigos",
      "church",
      "organ",
      "music",
      "concert",
      "noon",
      "listening",
    ],
  },
  "let-the-market-write-your-menu": {
    modes: ["at-table"],
    time: "own-pace",
    keywords: [
      "Porto",
      "Bolhão",
      "market",
      "food",
      "cheese",
      "conservas",
      "shopping",
      "ingredients",
    ],
  },
  "find-a-place-through-its-scent": {
    modes: ["watch-listen", "slow-down"],
    time: "short",
    keywords: [
      "Kyoto",
      "Kunjyukan",
      "Shoyeido",
      "incense",
      "scent",
      "fragrance",
      "Koh-labo",
      "gallery",
      "free",
    ],
  },
  "draw-a-small-shape-in-flame": {
    modes: ["hands-on"],
    time: "short",
    keywords: [
      "Venice",
      "Castello",
      "Huang Xiaozhe",
      "glass",
      "lampworking",
      "flame",
      "workshop",
      "atelier",
    ],
  },
  "lift-a-pattern-from-the-water": {
    modes: ["hands-on"],
    time: "short",
    keywords: [
      "Istanbul",
      "ebru",
      "marbling",
      "paper",
      "painting",
      "Sultanahmet",
      "Les Arts Turcs",
      "workshop",
    ],
  },
  "hear-the-arena-answer-back": {
    modes: ["watch-listen"],
    time: "calendar",
    keywords: [
      "Mexico City",
      "Arena México",
      "lucha libre",
      "wrestling",
      "CMLL",
      "evening",
      "spectator",
      "show",
    ],
  },
  "begin-with-rice-not-the-bottle": {
    modes: ["hands-on", "at-table"],
    time: "half-day",
    keywords: [
      "Seoul",
      "makgeolli",
      "brewing",
      "fermentation",
      "rice wine",
      "nuruk",
      "Sool Company",
      "workshop",
    ],
  },
  "let-the-dog-read-the-forest": {
    modes: ["outdoors", "at-table", "watch-listen"],
    time: "short",
    keywords: [
      "Istria",
      "Buzet",
      "Paladini",
      "Karlić",
      "truffle",
      "dog",
      "forest",
      "Croatia",
      "tasting",
    ],
  },
  "taste-what-time-does-to-port": {
    modes: ["at-table", "watch-listen"],
    time: "own-pace",
    keywords: [
      "Vila Nova de Gaia",
      "Porto",
      "Douro",
      "Port wine",
      "cellar",
      "Taylor's",
      "tasting",
      "wine",
    ],
  },
  "let-the-rainforest-be-introduced": {
    modes: ["outdoors", "watch-listen"],
    time: "short",
    keywords: [
      "Mossman Gorge",
      "Queensland",
      "Australia",
      "Daintree",
      "Kuku Yalanji",
      "Ngadiku",
      "Dreamtime",
      "Indigenous guided walk",
      "rainforest",
    ],
  },
  "find-the-citys-wilder-edge": {
    modes: ["outdoors", "slow-down"],
    time: "half-day",
    keywords: [
      "Singapore",
      "Sungei Buloh",
      "Kranji",
      "mangrove",
      "wetland",
      "birds",
      "birdwatching",
      "Kingfisher Pod",
      "walking",
    ],
  },
  "spend-an-hour-between-the-hot-rooms": {
    modes: ["slow-down"],
    time: "half-day",
    keywords: [
      "Busan",
      "South Korea",
      "jjimjilbang",
      "bathhouse",
      "sauna",
      "hot spring",
      "Spa Land",
      "Centum City",
    ],
  },
  "step-from-smoke-sauna-into-the-lake": {
    modes: ["slow-down", "watch-listen", "at-table"],
    time: "calendar",
    keywords: [
      "Kuopio",
      "Finland",
      "smoke sauna",
      "Lake Kallavesi",
      "winter swimming",
      "Jätkänkämppä",
      "Tuesday",
      "live music",
    ],
  },
  "cut-the-first-piece-of-a-pattern": {
    modes: ["hands-on"],
    time: "short",
    keywords: [
      "Fez",
      "Morocco",
      "zellige",
      "mosaic",
      "tile",
      "pottery",
      "ceramics",
      "artisan workshop",
    ],
  },
  "find-the-pulse-before-the-parade": {
    modes: ["hands-on", "watch-listen"],
    time: "calendar",
    keywords: [
      "Montevideo",
      "Uruguay",
      "candombe",
      "drum",
      "percussion",
      "rhythm",
      "older adults",
      "Friday",
    ],
  },
  "let-the-ferry-redraw-istanbul": {
    modes: ["outdoors", "slow-down"],
    time: "short",
    keywords: [
      "Istanbul",
      "Türkiye",
      "ferry",
      "Bosphorus",
      "Şehir Hatları",
      "public transport",
      "Europe",
      "Asia",
    ],
  },
  "ride-the-avenue-when-the-cars-step-aside": {
    modes: ["hands-on", "outdoors"],
    time: "calendar",
    keywords: [
      "Mexico City",
      "Paseo de la Reforma",
      "Muévete en Bici",
      "Sunday",
      "cycling",
      "bike",
      "walking",
      "skating",
    ],
  },
  "let-the-caller-start-the-dance": {
    modes: ["hands-on", "watch-listen"],
    time: "calendar",
    keywords: [
      "Edinburgh",
      "Scotland",
      "ceilidh",
      "dance",
      "caller",
      "live music",
      "Assembly Roxy",
      "Summerhall",
    ],
  },
  "follow-the-festa-through-the-streets": {
    modes: ["watch-listen", "outdoors"],
    time: "calendar",
    keywords: [
      "Malta",
      "Gozo",
      "festa",
      "village feast",
      "band",
      "procession",
      "fireworks",
      "festival",
    ],
  },
  "follow-the-agave-into-the-still": {
    modes: ["watch-listen", "at-table"],
    time: "short",
    keywords: [
      "Oaxaca",
      "Santiago Matatlán",
      "mezcal",
      "agave",
      "palenque",
      "distillery",
      "copper still",
      "tasting",
    ],
  },
  "read-the-language-of-the-coffee-cup": {
    modes: ["hands-on", "at-table", "watch-listen"],
    time: "short",
    keywords: [
      "Doha",
      "Qatar",
      "Souq Al Wakrah",
      "qahwa",
      "Arabic coffee",
      "coffee ceremony",
      "majlis",
      "Embrace Doha",
    ],
  },
  "stay-while-the-zamba-circles-back": {
    modes: ["watch-listen", "at-table"],
    time: "calendar",
    keywords: [
      "Salta",
      "Argentina",
      "peña",
      "Balderrama",
      "zamba",
      "folk music",
      "dance",
      "live music",
      "dinner",
    ],
  },
  "draw-with-wax-in-kampong-gelam": {
    modes: ["hands-on"],
    time: "short",
    keywords: [
      "Singapore",
      "Kampong Gelam",
      "batik",
      "batik tulis",
      "canting",
      "textile workshop",
      "wax resist",
    ],
  },
  "walk-the-island-between-forest-and-shore": {
    modes: ["outdoors", "slow-down"],
    time: "short",
    keywords: [
      "Singapore",
      "Coney Island",
      "Pulau Serangoon",
      "nature walk",
      "mangroves",
      "coastal forest",
      "birdwatching",
    ],
  },
  "build-a-pattern-in-colour": {
    modes: ["hands-on"],
    time: "short",
    keywords: [
      "Kyoto",
      "Yuzen",
      "Surikomi",
      "stencil",
      "textile",
      "dyeing",
      "Marumasu Nishimuraya",
      "machiya",
      "workshop",
    ],
  },
  "ride-from-alley-to-river": {
    modes: ["hands-on", "outdoors"],
    time: "half-day",
    keywords: [
      "Kyoto",
      "cycling",
      "bicycle",
      "bike",
      "Gion",
      "Kamo River",
      "Miyagawacho",
      "Shirakawa",
      "Kyoto Gyoen",
    ],
  },
  "when-the-herds-come-down": {
    modes: ["watch-listen", "outdoors"],
    time: "calendar",
    keywords: [
      "Allgäu",
      "Viehscheid",
      "cattle",
      "Alpine festival",
      "Thalkirchdorf",
      "Oberstaufen",
      "September",
    ],
  },
  "set-one-bell-in-motion": {
    modes: ["hands-on", "watch-listen"],
    time: "short",
    keywords: [
      "Cambridge",
      "bell ringing",
      "change ringing",
      "church bells",
      "campanology",
    ],
  },
  "paint-the-pattern-you-noticed": {
    modes: ["hands-on"],
    time: "short",
    keywords: [
      "Porto",
      "azulejo",
      "tile painting",
      "ceramics",
      "workshop",
      "Campanhã",
    ],
  },
  "spend-the-night-in-a-temple-town": {
    modes: ["slow-down"],
    time: "overnight",
    keywords: [
      "Koyasan",
      "Mount Koya",
      "temple stay",
      "shukubo",
      "Japan",
      "Buddhist lodging",
    ],
  },
  "cook-beyond-the-postcard": {
    modes: ["hands-on", "at-table"],
    time: "half-day",
    keywords: [
      "Cape Town",
      "Bo-Kaap",
      "Cape Malay",
      "cooking class",
      "spices",
      "samoosas",
      "masala",
    ],
  },
  "learn-the-fold-in-salta": {
    modes: ["hands-on", "at-table"],
    keywords: [
      "Salta",
      "Argentina",
      "empanada",
      "cooking workshop",
      "recado",
      "repulgue",
      "food",
    ],
  },
  "let-the-coffee-take-its-time": {
    modes: ["at-table", "watch-listen", "slow-down"],
    time: "half-day",
    keywords: [
      "Sarajevo",
      "Baščaršija",
      "Bosnian coffee",
      "cafe",
      "Old Town",
      "guided walk",
    ],
  },
  "let-the-drum-lead-the-first-step": {
    modes: ["hands-on", "watch-listen"],
    time: "calendar",
    keywords: [
      "Loíza",
      "Puerto Rico",
      "bomba",
      "dance class",
      "drumming",
      "percussion",
    ],
  },
  "play-the-wall-in-biarritz": {
    modes: ["hands-on"],
    time: "short",
    keywords: [
      "Biarritz",
      "Basque",
      "pelota",
      "pala",
      "chistera",
      "fronton",
      "Jai Alai",
      "sport",
      "beginner",
    ],
  },
  "watch-a-stage-made-of-water": {
    modes: ["watch-listen"],
    keywords: [
      "Hanoi",
      "Thang Long",
      "water puppetry",
      "theatre",
      "performance",
      "Hoan Kiem",
      "Vietnam",
    ],
  },
  "a-bowl-of-attention": {
    modes: ["hands-on", "at-table", "slow-down"],
    time: "short",
    keywords: ["tea", "matcha", "Kyoto", "Japan", "tea ceremony"],
  },
  "venice-through-an-oar": {
    modes: ["hands-on", "outdoors"],
    time: "short",
    keywords: ["rowing", "boat", "water", "lagoon", "voga"],
  },
  "marble-steam-istanbul": {
    modes: ["slow-down"],
    time: "short",
    keywords: [
      "hammam",
      "hamam",
      "Turkish bath",
      "bathing",
      "steam",
      "architecture",
    ],
  },
  "the-pour-before-the-glass": {
    modes: ["hands-on", "at-table"],
    time: "short",
    keywords: ["cider", "cellar", "apple", "tasting", "sidra"],
  },
  "colour-before-cloth": {
    modes: ["hands-on"],
    time: "half-day",
    keywords: [
      "dyeing",
      "dye",
      "textile",
      "craft",
      "workshop",
      "colour",
      "color",
    ],
  },
  "mexico-city-grown-on-water": {
    modes: ["outdoors", "at-table"],
    time: "half-day",
    keywords: ["chinampa", "farm", "food", "boat", "breakfast", "Xochimilco"],
  },
  "read-the-desert-at-ground-level": {
    modes: ["outdoors", "watch-listen"],
    time: "half-day",
    keywords: ["desert", "wildlife", "dunes", "chameleon", "Namib"],
  },
  "a-morning-at-the-hawker-table": {
    modes: ["at-table"],
    time: "own-pace",
    keywords: ["street food", "breakfast", "hawker", "Singapore", "market"],
  },
  "a-city-in-the-water": {
    modes: ["slow-down"],
    time: "own-pace",
    keywords: ["swim", "swimming", "pool", "Reykjavik", "water"],
  },
  "make-room-in-the-steam": {
    modes: ["slow-down"],
    time: "own-pace",
    keywords: ["sauna", "steam", "Tampere", "bathing"],
  },
  "the-vineyard-at-the-table": {
    modes: ["at-table"],
    time: "own-pace",
    keywords: ["wine", "dinner", "heuriger", "Vienna", "vineyard"],
  },
  "leave-room-for-devotion": {
    modes: ["outdoors", "slow-down"],
    time: "own-pace",
    keywords: [
      "walk",
      "walking",
      "forest",
      "Kumano",
      "Daimon-zaka",
      "pilgrimage",
    ],
  },
  "the-fish-behind-the-islands": {
    modes: ["watch-listen"],
    time: "own-pace",
    keywords: ["museum", "fishing", "stockfish", "skrei", "Lofoten"],
  },
  "stay-for-the-session": {
    modes: ["watch-listen", "at-table"],
    time: "calendar",
    keywords: ["music", "live music", "evening", "pub", "Doolin"],
  },
  "step-into-the-dance": {
    modes: ["hands-on", "watch-listen"],
    time: "calendar",
    keywords: ["dance", "dancing", "music", "evening", "tanchaz"],
  },
  "the-weight-of-the-tower": {
    modes: ["watch-listen", "outdoors"],
    time: "calendar",
    keywords: ["castells", "human towers", "Barcelona", "festival"],
  },
  "walk-where-the-sea-was": {
    modes: ["outdoors"],
    time: "calendar",
    keywords: ["walk", "walking", "mudflat", "tide", "Wadden"],
  },
  "the-tide-brings-the-horses": {
    modes: ["watch-listen", "outdoors"],
    time: "calendar",
    keywords: ["horses", "fishing", "shrimp", "beach", "tide"],
  },
  "when-the-sky-moves-as-one": {
    modes: ["outdoors", "watch-listen"],
    time: "calendar",
    keywords: [
      "birds",
      "birdwatching",
      "starlings",
      "wildlife",
      "sunset",
      "black sun",
    ],
  },
  "when-the-sap-starts-to-run": {
    modes: ["at-table"],
    time: "calendar",
    keywords: ["maple", "sugar shack", "spring", "Quebec"],
  },
  "kimchi-before-the-jar": {
    modes: ["hands-on", "at-table"],
    keywords: ["kimchi", "cooking", "class", "fermentation", "Seoul"],
  },
  "bread-from-the-tonir": {
    modes: ["hands-on", "at-table"],
    keywords: ["bread", "baking", "lavash", "tonir", "Armenia"],
  },
  "before-the-chocolate-bar": {
    modes: ["watch-listen", "at-table"],
    keywords: ["cacao", "cocoa", "chocolate", "estate", "Grenada"],
  },
  "follow-appenzeller-from-vat-to-cellar": {
    modes: ["watch-listen", "at-table"],
    time: "own-pace",
    keywords: [
      "cheese",
      "cheese making",
      "dairy",
      "production",
      "Appenzell",
      "Switzerland",
    ],
  },
  "watch-a-dhow-take-shape-beside-the-creek": {
    modes: ["watch-listen", "outdoors"],
    time: "own-pace",
    keywords: [
      "dhow",
      "boat building",
      "shipyard",
      "craft",
      "Ajman",
      "United Arab Emirates",
    ],
  },
  "read-monument-valley-beyond-the-scenic-drive": {
    modes: ["watch-listen", "outdoors"],
    time: "half-day",
    keywords: [
      "Monument Valley",
      "Navajo",
      "Diné",
      "Dine",
      "tribal park",
      "guide",
      "backcountry",
      "desert",
      "United States",
    ],
  },
  "follow-balis-water-before-the-rice": {
    modes: ["watch-listen", "outdoors"],
    time: "half-day",
    keywords: [
      "Bali",
      "Jatiluwih",
      "Indonesia",
      "subak",
      "rice terraces",
      "irrigation",
      "water",
      "farmer",
      "trekking",
    ],
  },
  "make-tea-before-taipei-drinks-it": {
    modes: ["hands-on", "at-table", "outdoors"],
    time: "half-day",
    keywords: [
      "Pinglin",
      "New Taipei",
      "Taiwan",
      "tea",
      "Baozhong",
      "Pouchong",
      "tea picking",
      "tea making",
      "farm",
    ],
  },
};
