import type { DiscoveryProfile } from "./discovery-profiles";

export const edition20260925 = {
  "eat-drink": [
    "follow-the-mung-bean-to-the-hot-pan",
    "taste-lyon-one-market-counter-at-a-time",
    "taste-what-changes-inside-a-spoonful",
  ],
  "make-learn": [
    "give-delft-blue-a-line-of-your-own",
    "build-a-scent-one-decision-at-a-time",
    "make-a-lunch-you-cannot-eat",
  ],
  "move-water": [
    "paddle-below-waterlands-low-bridges",
    "join-vancouvers-edges-by-bicycle",
    "see-table-mountain-from-a-kayak",
  ],
  "explore-reflect": [
    "look-for-the-life-too-small-to-see",
    "read-the-stream-beneath-seouls-streets",
    "let-the-garden-be-introduced-through-country",
  ],
  "swim-reset": [
    "meet-baths-warm-water-under-open-sky",
    "give-baden-three-hours-of-warm-water",
    "let-oslos-waterline-set-a-slower-pace",
  ],
  "shared-rituals": [
    "let-the-caller-bring-you-into-the-dance",
    "give-lunch-half-an-hour-of-listening",
    "begin-kabuki-with-a-single-act",
  ],
} as const;

export const discoveryBatch42: Record<string, DiscoveryProfile> = {
  "follow-the-mung-bean-to-the-hot-pan": {
    modes: ["at-table", "watch-listen"],
    time: "own-pace",
    keywords: [
      "Seoul",
      "Jongno",
      "Gwangjang",
      "Soonheenae",
      "bindaetteok",
      "mung bean",
      "pancake",
      "market",
      "street food",
    ],
  },
  "taste-lyon-one-market-counter-at-a-time": {
    modes: ["at-table", "watch-listen"],
    time: "half-day",
    keywords: [
      "Lyon",
      "Halles",
      "Paul Bocuse",
      "Lyon Food Tour",
      "ONLYLYON",
      "cheese",
      "quenelle",
      "praline",
      "tasting",
    ],
  },
  "taste-what-changes-inside-a-spoonful": {
    modes: ["at-table", "watch-listen"],
    time: "short",
    keywords: [
      "Bologna",
      "Anzola dell'Emilia",
      "Carpigiani",
      "Gelatology",
      "gelato",
      "ice cream",
      "tasting",
      "museum",
    ],
  },
  "give-delft-blue-a-line-of-your-own": {
    modes: ["hands-on"],
    time: "short",
    keywords: [
      "Delft",
      "Royal Delft",
      "Delftware",
      "blue and white",
      "ceramic",
      "tile",
      "painting",
      "workshop",
    ],
  },
  "build-a-scent-one-decision-at-a-time": {
    modes: ["hands-on"],
    time: "short",
    keywords: [
      "Grasse",
      "Galimard",
      "Studio des Fragrances",
      "perfume",
      "scent",
      "fragrance",
      "composition",
      "workshop",
    ],
  },
  "make-a-lunch-you-cannot-eat": {
    modes: ["hands-on"],
    time: "short",
    keywords: [
      "Tokyo",
      "Kappabashi",
      "Asakusa",
      "Ganso",
      "shokuhin sample",
      "wax",
      "food replica",
      "tempura",
      "lettuce",
    ],
  },
  "paddle-below-waterlands-low-bridges": {
    modes: ["outdoors", "hands-on"],
    time: "short",
    keywords: [
      "Watergang",
      "Waterland",
      "near Amsterdam",
      "Wetlands Safari",
      "Fresh Air",
      "canoe",
      "reeds",
      "bridges",
    ],
  },
  "join-vancouvers-edges-by-bicycle": {
    modes: ["outdoors", "watch-listen"],
    time: "full-day",
    keywords: [
      "Vancouver",
      "Cycle City",
      "Grand Tour",
      "Stanley Park",
      "seawall",
      "Granville Island",
      "Gastown",
      "cycling",
    ],
  },
  "see-table-mountain-from-a-kayak": {
    modes: ["outdoors", "hands-on"],
    time: "short",
    keywords: [
      "Cape Town",
      "Granger Bay",
      "Table Mountain",
      "Kayak Adventures",
      "sea kayak",
      "paddling",
      "ocean",
    ],
  },
  "look-for-the-life-too-small-to-see": {
    modes: ["watch-listen"],
    time: "own-pace",
    keywords: [
      "Amsterdam",
      "Plantage",
      "ARTIS",
      "Micropia",
      "microbes",
      "microscope",
      "science",
      "museum",
    ],
  },
  "read-the-stream-beneath-seouls-streets": {
    modes: ["watch-listen", "outdoors"],
    time: "own-pace",
    keywords: [
      "Seoul",
      "Cheonggyecheon",
      "museum",
      "stream",
      "urban history",
      "water",
      "infrastructure",
      "free",
    ],
  },
  "let-the-garden-be-introduced-through-country": {
    modes: ["watch-listen", "outdoors"],
    time: "short",
    keywords: [
      "Melbourne",
      "Royal Botanic Gardens",
      "Aboriginal Heritage Walk",
      "First Peoples",
      "Country",
      "Eastern Kulin",
      "plants",
      "guided walk",
    ],
  },
  "meet-baths-warm-water-under-open-sky": {
    modes: ["slow-down"],
    time: "short",
    keywords: [
      "Bath",
      "Thermae",
      "thermal",
      "rooftop pool",
      "Minerva",
      "bathing",
      "warm water",
    ],
  },
  "give-baden-three-hours-of-warm-water": {
    modes: ["slow-down"],
    time: "half-day",
    keywords: [
      "Baden",
      "Switzerland",
      "FORTYSEVEN",
      "thermal pools",
      "bathing",
      "warm water",
      "rest",
    ],
  },
  "let-oslos-waterline-set-a-slower-pace": {
    modes: ["slow-down", "outdoors"],
    time: "short",
    keywords: [
      "Oslo",
      "KOK",
      "Langkaia",
      "Aker Brygge",
      "shared sauna",
      "fjord",
      "dockside",
      "waterfront",
    ],
  },
  "let-the-caller-bring-you-into-the-dance": {
    modes: ["hands-on", "watch-listen"],
    time: "calendar",
    keywords: [
      "Glasgow",
      "Sloans",
      "ceilidh",
      "Friday",
      "dance",
      "live band",
      "caller",
      "ballroom",
    ],
  },
  "give-lunch-half-an-hour-of-listening": {
    modes: ["watch-listen"],
    time: "calendar",
    keywords: [
      "Amsterdam",
      "Concertgebouw",
      "lunchconcert",
      "lunchtime",
      "classical music",
      "concert",
      "rehearsal",
      "free",
    ],
  },
  "begin-kabuki-with-a-single-act": {
    modes: ["watch-listen"],
    time: "calendar",
    keywords: [
      "Tokyo",
      "Ginza",
      "Kabukiza",
      "kabuki",
      "Shochiku",
      "single act",
      "theatre",
      "caption",
    ],
  },
};
