import type { DiscoveryProfile } from "./discovery-profiles";

export const edition20260924 = {
  "eat-drink": [
    "taste-melbourne-across-the-market-counter",
    "taste-tea-from-the-tap-and-the-pour",
    "follow-cacao-from-the-museum-to-the-cup",
  ],
  "make-learn": [
    "shape-a-cup-without-a-wheel",
    "cut-a-line-that-catches-the-light",
    "build-the-curry-before-the-wok",
  ],
  "move-water": [
    "learn-to-read-the-water-before-standing",
    "follow-bangkok-at-the-width-of-a-bicycle",
    "ride-between-buenos-aires-city-stories",
  ],
  "explore-reflect": [
    "see-singapore-at-the-scale-of-a-model",
    "let-a-garden-guide-change-what-you-notice",
    "read-a-wall-of-words-before-they-print",
  ],
  "swim-reset": [
    "give-tokyo-an-hour-at-the-bathhouse",
    "swim-a-london-length-under-open-sky",
    "leave-room-between-rotoruas-warm-pools",
  ],
  "shared-rituals": [
    "watch-a-story-travel-through-a-gesture",
    "hear-the-band-without-a-screen-between-you",
    "hear-seoul-change-tempo-on-a-saturday",
  ],
} as const;

export const discoveryBatch41: Record<string, DiscoveryProfile> = {
  "taste-melbourne-across-the-market-counter": {
    modes: ["at-table", "watch-listen"],
    time: "short",
    keywords: [
      "Melbourne",
      "Queen Victoria Market",
      "QVM",
      "Ultimate Foodie Tour",
      "food",
      "tasting",
      "market",
      "traders",
    ],
  },
  "taste-tea-from-the-tap-and-the-pour": {
    modes: ["at-table"],
    time: "short",
    keywords: [
      "Taipei",
      "Datong",
      "Wangtea Lab",
      "tea",
      "draft",
      "pour-over",
      "nitrogen",
      "brewing",
    ],
  },
  "follow-cacao-from-the-museum-to-the-cup": {
    modes: ["at-table", "watch-listen"],
    time: "own-pace",
    keywords: [
      "Mexico City",
      "MUCHO",
      "chocolate",
      "cacao",
      "Juárez",
      "museum",
      "drink",
      "Milan",
    ],
  },
  "shape-a-cup-without-a-wheel": {
    modes: ["hands-on"],
    time: "half-day",
    keywords: [
      "Lisbon",
      "Alcântara",
      "PURACERÂMICA",
      "ceramics",
      "pottery",
      "handbuilding",
      "clay",
      "firing",
      "English",
    ],
  },
  "cut-a-line-that-catches-the-light": {
    modes: ["hands-on"],
    time: "short",
    keywords: [
      "Tokyo",
      "Sokichi",
      "Asakusa",
      "Kaminarimon",
      "kiriko",
      "cut glass",
      "workshop",
      "same-day",
    ],
  },
  "build-the-curry-before-the-wok": {
    modes: ["hands-on", "at-table"],
    time: "half-day",
    keywords: [
      "Bangkok",
      "Silom",
      "Sompong",
      "Thai cooking",
      "curry paste",
      "market",
      "Popular Menu",
      "wok",
    ],
  },
  "learn-to-read-the-water-before-standing": {
    modes: ["hands-on", "outdoors"],
    time: "short",
    keywords: [
      "Sydney",
      "Manly",
      "surf",
      "surfing",
      "adult group",
      "ocean",
      "beginner",
      "swimming ability",
    ],
  },
  "follow-bangkok-at-the-width-of-a-bicycle": {
    modes: ["outdoors", "watch-listen"],
    time: "half-day",
    keywords: [
      "Bangkok",
      "Chinatown",
      "Thonburi",
      "Co van Kessel",
      "Co Classical",
      "cycling",
      "River City",
      "bicycle",
    ],
  },
  "ride-between-buenos-aires-city-stories": {
    modes: ["outdoors", "watch-listen"],
    time: "half-day",
    keywords: [
      "Buenos Aires",
      "BA Bikes",
      "South Circuit",
      "San Telmo",
      "La Boca",
      "Plaza de Mayo",
      "Puerto Madero",
      "cycling",
    ],
  },
  "see-singapore-at-the-scale-of-a-model": {
    modes: ["watch-listen"],
    time: "own-pace",
    keywords: [
      "Singapore",
      "URA",
      "City Gallery",
      "city model",
      "urban planning",
      "architecture",
      "free",
      "exhibition",
    ],
  },
  "let-a-garden-guide-change-what-you-notice": {
    modes: ["outdoors", "watch-listen"],
    time: "short",
    keywords: [
      "Cape Town",
      "Kirstenbosch",
      "SANBI",
      "botanical garden",
      "plants",
      "volunteer walk",
      "seasonal",
      "nature",
    ],
  },
  "read-a-wall-of-words-before-they-print": {
    modes: ["watch-listen"],
    time: "short",
    keywords: [
      "Taipei",
      "Datong",
      "Ri Xing",
      "Rixing",
      "type foundry",
      "letterpress",
      "movable type",
      "printing",
      "Chinese characters",
    ],
  },
  "give-tokyo-an-hour-at-the-bathhouse": {
    modes: ["slow-down"],
    time: "own-pace",
    keywords: [
      "Tokyo",
      "Negishi",
      "Uguisudani",
      "Hagino-yu",
      "Haginoyu",
      "sento",
      "bathhouse",
      "bathing",
    ],
  },
  "swim-a-london-length-under-open-sky": {
    modes: ["slow-down", "outdoors"],
    time: "own-pace",
    keywords: [
      "London",
      "Parliament Hill Lido",
      "Hampstead Heath",
      "outdoor swimming",
      "unheated",
      "pool",
      "public",
      "seasonal",
    ],
  },
  "leave-room-between-rotoruas-warm-pools": {
    modes: ["slow-down", "outdoors"],
    time: "own-pace",
    keywords: [
      "Rotorua",
      "New Zealand",
      "Polynesian Spa",
      "Pavilion Pools",
      "geothermal",
      "bathing",
      "lake",
      "rest",
    ],
  },
  "watch-a-story-travel-through-a-gesture": {
    modes: ["watch-listen"],
    time: "calendar",
    keywords: [
      "Bangkok",
      "Sala Chalermkrung",
      "khon",
      "Thai dance",
      "theatre",
      "Grand Palace",
      "music",
      "subtitles",
    ],
  },
  "hear-the-band-without-a-screen-between-you": {
    modes: ["watch-listen"],
    time: "calendar",
    keywords: [
      "New Orleans",
      "Preservation Hall",
      "jazz",
      "French Quarter",
      "live music",
      "ensemble",
      "listening",
      "all ages",
    ],
  },
  "hear-seoul-change-tempo-on-a-saturday": {
    modes: ["watch-listen"],
    time: "calendar",
    keywords: [
      "Seoul",
      "National Gugak Center",
      "Umyeondang",
      "Saturday",
      "gugak",
      "Korean music",
      "dance",
      "concert",
    ],
  },
};
