import type { DiscoveryProfile } from "./discovery-profiles";

/** Each guide counts once towards the daily edition, even when search interests overlap. */
export const edition20260923 = {
  "eat-drink": [
    "taste-balsamico-before-it-meets-the-plate",
    "meet-tokyo-in-a-cup-of-dashi",
    "follow-lambic-from-the-brewery-to-the-glass",
  ],
  "make-learn": [
    "draw-a-sheet-on-floating-colour",
    "repair-a-bowl-without-hiding-the-join",
    "stitch-the-pair-you-take-home",
  ],
  "move-water": [
    "try-the-games-before-you-watch-the-match",
    "paddle-between-stockholms-island-edges",
    "stand-at-river-level-in-ljubljana",
  ],
  "explore-reflect": [
    "cross-lisbon-on-the-route-of-its-water",
    "read-the-veld-with-a-san-guide",
    "read-naples-below-the-street",
  ],
  "swim-reset": [
    "give-helsinki-time-between-the-heat",
    "let-budapest-slow-to-the-pool",
    "meet-la-concha-through-warm-seawater",
  ],
  "shared-rituals": [
    "let-the-fado-room-fall-quiet",
    "learn-the-step-before-joining-the-floor",
    "listen-for-the-conversation-inside-flamenco",
  ],
} as const;

export const discoveryBatch40: Record<string, DiscoveryProfile> = {
  "taste-balsamico-before-it-meets-the-plate": {
    modes: ["at-table", "watch-listen"],
    time: "short",
    keywords: [
      "Modena",
      "Giusti",
      "balsamic",
      "balsamico",
      "acetaia",
      "vinegar",
      "tasting",
      "barrels",
    ],
  },
  "meet-tokyo-in-a-cup-of-dashi": {
    modes: ["at-table"],
    time: "short",
    keywords: [
      "Tokyo",
      "Nihonbashi",
      "Ninben",
      "dashi",
      "broth",
      "katsuobushi",
      "fish",
      "counter",
    ],
  },
  "follow-lambic-from-the-brewery-to-the-glass": {
    modes: ["at-table", "watch-listen"],
    time: "short",
    keywords: [
      "Brussels",
      "Cantillon",
      "lambic",
      "gueuze",
      "beer",
      "brewery",
      "tasting",
      "fermentation",
    ],
  },
  "draw-a-sheet-on-floating-colour": {
    modes: ["hands-on", "watch-listen"],
    keywords: [
      "Florence",
      "Il Papiro",
      "marbling",
      "paper",
      "bookbinding",
      "workshop",
      "colour",
    ],
  },
  "repair-a-bowl-without-hiding-the-join": {
    modes: ["hands-on"],
    time: "short",
    keywords: [
      "Kyoto",
      "Shikata",
      "kintsugi",
      "urushi",
      "lacquer",
      "repair",
      "ceramics",
      "workshop",
    ],
  },
  "stitch-the-pair-you-take-home": {
    modes: ["hands-on"],
    time: "short",
    keywords: [
      "Barcelona",
      "espadrilles",
      "HANDMADE",
      "stitching",
      "shoes",
      "workshop",
      "craft",
    ],
  },
  "try-the-games-before-you-watch-the-match": {
    modes: ["hands-on", "outdoors"],
    keywords: [
      "Dublin",
      "Na Fianna",
      "Glasnevin",
      "hurling",
      "Gaelic football",
      "handball",
      "sport",
      "beginner",
    ],
  },
  "paddle-between-stockholms-island-edges": {
    modes: ["hands-on", "outdoors"],
    time: "short",
    keywords: [
      "Stockholm",
      "Tantolunden",
      "Långholmen",
      "kayak",
      "tandem",
      "guided",
      "water",
      "swimming required",
    ],
  },
  "stand-at-river-level-in-ljubljana": {
    modes: ["hands-on", "outdoors"],
    time: "short",
    keywords: [
      "Ljubljana",
      "Ljubljanica",
      "Bananaway",
      "SUP",
      "paddleboarding",
      "river",
      "Špica",
      "guided",
    ],
  },
  "cross-lisbon-on-the-route-of-its-water": {
    modes: ["watch-listen", "outdoors"],
    time: "own-pace",
    keywords: [
      "Lisbon",
      "Águas Livres",
      "aqueduct",
      "water",
      "engineering",
      "Campolide",
      "museum",
      "architecture",
    ],
  },
  "read-the-veld-with-a-san-guide": {
    modes: ["watch-listen", "outdoors"],
    time: "short",
    keywords: [
      "South Africa",
      "West Coast",
      "Khwa ttu",
      "San",
      "tracking",
      "veld",
      "guide",
      "nature",
    ],
  },
  "read-naples-below-the-street": {
    modes: ["watch-listen"],
    time: "short",
    keywords: [
      "Naples",
      "Galleria Borbonica",
      "Bourbon tunnel",
      "underground",
      "cistern",
      "Standard route",
      "history",
    ],
  },
  "give-helsinki-time-between-the-heat": {
    modes: ["slow-down"],
    time: "short",
    keywords: [
      "Helsinki",
      "Löyly",
      "sauna",
      "smoke sauna",
      "Hernesaari",
      "Baltic",
      "rest",
      "architecture",
    ],
  },
  "let-budapest-slow-to-the-pool": {
    modes: ["slow-down"],
    time: "own-pace",
    keywords: [
      "Budapest",
      "Széchenyi",
      "thermal",
      "bath",
      "pool",
      "daytime",
      "bathing",
    ],
  },
  "meet-la-concha-through-warm-seawater": {
    modes: ["slow-down"],
    time: "half-day",
    keywords: [
      "San Sebastián",
      "Donostia",
      "La Perla",
      "La Concha",
      "seawater",
      "circuit",
      "spa",
      "rest",
    ],
  },
  "let-the-fado-room-fall-quiet": {
    modes: ["watch-listen", "at-table"],
    time: "calendar",
    keywords: [
      "Lisbon",
      "Alfama",
      "Mesa de Frades",
      "fado",
      "dinner",
      "music",
      "tiles",
    ],
  },
  "learn-the-step-before-joining-the-floor": {
    modes: ["hands-on", "watch-listen"],
    time: "calendar",
    keywords: [
      "Buenos Aires",
      "Palermo",
      "La Viruta Tango AR",
      "tango",
      "milonga",
      "dance",
      "beginner",
    ],
  },
  "listen-for-the-conversation-inside-flamenco": {
    modes: ["watch-listen"],
    time: "calendar",
    keywords: [
      "Madrid",
      "Cardamomo",
      "flamenco",
      "tablao",
      "guitar",
      "cante",
      "palmas",
      "Barrio de las Letras",
    ],
  },
};
