import type { GuideMedia } from "./media";

const official = (
  guideId: string,
  title: string,
  alt: string,
  photographer: string,
  sourceUrl: string,
  rationale: string,
  depiction: string,
): GuideMedia => ({
  guideId,
  src: `/images/guides/${guideId}.jpg`,
  title,
  alt,
  photographer,
  sourceUrl,
  licenseName:
    "Official source photograph. Reuse rights not independently cleared",
  licenseUrl: sourceUrl,
  rightsBasis: "official_source",
  rightsCheckedOn: "2026-09-25",
  visualReview: { outcome: "approved", checkedOn: "2026-09-25", rationale },
  depiction: `${depiction} It does not prove EA attendance or guarantee future conditions. Reuse rights have not been independently cleared.`,
});

export const mediaBatch42: readonly GuideMedia[] = [
  {
    guideId: "seoul-gwangjang-bindaetteok",
    src: "/images/guides/seoul-gwangjang-bindaetteok.jpg",
    title: "Bindaetteok at Gwangjang Market",
    alt: "A vendor fries mung-bean pancakes on a broad hotplate beside stacks of cooked bindaetteok at Gwangjang Market.",
    photographer: "Rystheguy",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Frying_Bindaetteok.jpg",
    licenseName: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    rightsBasis: "documented_license",
    rightsCheckedOn: "2026-09-25",
    visualReview: {
      outcome: "approved",
      checkedOn: "2026-09-25",
      rationale:
        "The documentary frame makes batter, hotplate and finished pancakes legible together. It is specific to Gwangjang rather than a generic Korean food plate.",
    },
    depiction:
      "Photographed at Gwangjang Market on 2 January 2016. It does not identify the guide's suggested counter, current vendors or current prices. Resized and responsively cropped under the same CC BY-SA 4.0 license. No EA attendance or photographer endorsement is implied.",
  },
  official(
    "lyon-halles-tasting",
    "A bakery counter at Les Halles",
    "Loaves and baguettes fill a brass-edged display beside Jocteur bakery bags at Les Halles de Lyon Paul Bocuse.",
    "Halles de Lyon Paul Bocuse. Individual photographer not named",
    "https://www.halles-de-lyon-paulbocuse.com/",
    "The market's own 928-pixel photograph has clear bread texture, warm material detail and a specific trader identity. It replaces generic macaron and low-resolution tour thumbnails.",
    "A Jocteur bakery counter published by the market. It illustrates the venue's food trade, not a guaranteed tour stop or included bread tasting.",
  ),
  official(
    "bologna-gelatology",
    "Ingredients for a closer tasting",
    "Transparent containers hold berries, chopped nuts, chocolate pieces and colourful toppings in a display at the Gelato Museum.",
    "Carpigiani Gelato Museum. Individual photographer not named",
    "https://www.gelatomuseum.com/en/book-your-gelato-experience/gelatology-300",
    "The original programme-gallery photograph offers crisp small-scale food detail and a quiet background. Its varied cups support comparison without promotional overlays.",
    "An ingredient display in the programme gallery, not a photograph of an included tasting flight. Ingredients and serving format are not guaranteed.",
  ),
  official(
    "delft-tile-painting",
    "Painting at Royal Delft",
    "Two participants use small brushes on ceramic pieces at a table in front of a blue-and-white tiled wall at Royal Delft.",
    "Royal Delft Museum / InDelft. Individual photographer not named",
    "https://www.indelft.nl/nl/uitagenda/uitagenda-delft/3701544212/schilderworkshop-delfts-blauw",
    "The high-resolution tourism photograph shows attention, brushes and the actual workshop setting. The visitor's making role is clear without presenting an expert demonstration as their result.",
    "A Royal Delft painting-workshop illustration. The standard public booking described in this guide is a tile, not a promise of any other pictured ceramic form.",
  ),
  official(
    "grasse-galimard-perfume",
    "Composing at the Studio des Fragrances",
    "Participants work at individual semicircles of scent bottles in Galimard's bright perfume-creation studio.",
    "Galimard. Individual photographer not named",
    "https://www.galimard.com/en/studio-des-fragrances",
    "The 1024-pixel official creation-workshop photograph makes the scent organ and active participant role visible. It replaces an incorrectly associated Eze cologne thumbnail.",
    "The studio's creation-workshop photograph. The people, instructor and exact workstation allocation may differ.",
  ),
  official(
    "tokyo-ganso-wax-food",
    "Wax tempura and lettuce",
    "Realistic wax tempura pieces and green imitation lettuce sit on plates as food-replica examples at Ganso Sample-ya.",
    "IWASAKI / Ganso Shokuhin Sample-ya. Individual photographer not named",
    "https://www.ganso-sample.com/en/shop/kappabashi/experience/",
    "A clean, detailed image from the exact workshop page makes the improbable wax result instantly readable. The caption explicitly prevents confusion with edible food.",
    "Finished food-replica examples, not real food, a served meal or guaranteed identical participant results.",
  ),
  official(
    "watergang-wetlands-canoe",
    "Canoeing in Waterland",
    "Two people paddle a canoe along a narrow green channel bordered by reeds and water plants in Waterland.",
    "Wetlands Safari. Individual photographer not named",
    "https://www.wetlandssafari.nl/nl/english/2025-2/",
    "The clear 800-pixel programme photograph places the canoe within the reeds at human scale. Its colour and uncluttered route remain readable in a bounded responsive card.",
    "An operator photograph of the canoeing environment. Vegetation, route, weather and boat occupancy can vary.",
  ),
  official(
    "vancouver-grand-cycle",
    "Cycling through Vancouver",
    "Two helmeted cyclists ride past brick buildings and shopfronts on a Vancouver city street.",
    "Cycle City Vancouver. Individual photographer not named",
    "https://cyclevancouver.com/bike-tours/the-grand-tour/",
    "The high-resolution operator image connects bicycles with the street environment. Helmets and the city context are visible, without substituting advanced sport for a guided urban tour.",
    "An operator route photograph. It does not establish that every section is traffic-free or guarantee the same stops.",
  ),
  official(
    "cape-town-granger-kayak",
    "Cape Town from the water",
    "A small double kayak crosses blue water beneath Cape Town's waterfront buildings and the broad outline of Table Mountain.",
    "Kayak Adventures Cape Town. Individual photographer not named",
    "https://kayakadventures.capetown/cape-town-kayaking",
    "A sharp, spacious documentary view from the specific programme page connects a recognisable mountain with the small scale of paddling. No wildlife spectacle is used to imply a guarantee.",
    "The programme's coastal setting, not a forecast of water, wind, visibility or wildlife on a booked day.",
  ),
  official(
    "amsterdam-micropia",
    "Looking closely at Micropia",
    "Visitors lean toward illuminated circular culture displays arranged in rows inside ARTIS Micropia.",
    "ARTIS Micropia. Individual photographer not named",
    "https://www.artis.nl/en/artis-micropia",
    "The detailed museum image shows visitors actively looking at specimens. Light from the culture wall supplies a strong focal point without artificial visual effects.",
    "A museum display photograph, not a medical test, hands-on laboratory booking or guarantee that every installation is operating.",
  ),
  official(
    "seoul-cheonggyecheon-museum",
    "Cheonggyecheon Museum",
    "A curved glass facade rises above the pavement outside Cheonggyecheon Museum in Seoul.",
    "Seoul Museum of History. Individual photographer not named",
    "https://museum.seoul.go.kr/eng/about/annex/cheongGyeMuse.jsp",
    "The institution's clear 1100-pixel building photograph identifies the actual museum, avoiding a misleading image of the distant downtown plaza.",
    "The museum exterior. It is not a photograph of the entire stream route or evidence that outdoor paths are open.",
  ),
  official(
    "melbourne-aboriginal-garden-walk",
    "A closer look in Melbourne Gardens",
    "Two people look upward among dense tree ferns during a guided walk in Melbourne's Royal Botanic Gardens.",
    "City of Melbourne / Royal Botanic Gardens Victoria. Individual photographer not named",
    "https://whatson.melbourne.vic.gov.au/things-to-do/aboriginal-heritage-walk",
    "The city's programme-specific image has rich natural greens and a clear shared act of looking. It replaces an unrelated navigation image for another garden tour.",
    "A photograph published with the Aboriginal Heritage Walk listing. It does not guarantee a particular guide, plant encounter or permission to record cultural knowledge.",
  ),
  official(
    "bath-thermae-welcome",
    "Thermae's rooftop pool",
    "Bathers sit in a steaming rooftop pool with Bath Abbey and the city's stone buildings beyond the water.",
    "Thermae Bath Spa. Individual photographer not named",
    "https://www.thermaebathspa.com/",
    "The sharp official panorama links warm water to a recognisable Bath skyline. Its clear central subject survives the bounded detail and card crops.",
    "The contemporary Thermae rooftop pool, not the archaeological Roman Baths. Weather, crowds and visibility vary.",
  ),
  official(
    "baden-fortyseven-pools",
    "A pool at FORTYSEVEN",
    "One bather rests in an indoor thermal pool beneath timber ceilings and tall windows at FORTYSEVEN in Baden.",
    "Tobias Westen / ThermalBaden AG",
    "https://www.fortyseven.ch/en",
    "A high-resolution square image balances quiet architecture, water and a small human presence. The supplied source filename explicitly credits Tobias Westen and ThermalBaden AG.",
    "One public pool at the facility. Quiet occupancy and uninterrupted operation are not guaranteed.",
  ),
  official(
    "oslo-kok-shared-sauna",
    "Outside a KOK sauna",
    "Bathers in swimwear stand on the timber deck outside a floating KOK sauna beside a ladder into Oslo's water.",
    "KOK Norge. Individual photographer not named",
    "https://koknorge.no/en/",
    "The shared-sauna source photograph shows the actual deck, threshold and water access. It replaces a close-up of splashing that failed to identify the sauna experience.",
    "A KOK shared-sauna illustration, not a boat cruise, lifeguard promise or requirement to enter the fjord.",
  ),
  official(
    "glasgow-sloans-ceilidh",
    "A ceilidh in Sloans' ballroom",
    "Pairs dance in Sloans' Grand Ballroom beneath chandeliers and warm strings of lights.",
    "Sloans Glasgow. Individual photographer not named",
    "https://www.sloansglasgow.co.uk/ceilidh",
    "The high-resolution programme photograph places dancers in the actual ballroom and makes the social activity visible. It is not a generic Scottish landscape or staged costume image.",
    "An event photograph. Dancers, band, decorations and room occupancy can differ on another date.",
  ),
  official(
    "amsterdam-lunchtime-concert",
    "Listening at the Concertgebouw",
    "Musicians perform on a small stage in an ornate Concertgebouw hall with a seated audience in the foreground.",
    "Het Concertgebouw. Individual photographer not named",
    "https://www.concertgebouw.nl/lunchconcerten",
    "The programme's 908-pixel photograph holds the performers, room and audience in one coherent frame. It shows actual listening rather than only the building exterior.",
    "A 2025 lunchtime-series illustration. The current event may use another hall, ensemble or rehearsal format.",
  ),
  {
    guideId: "tokyo-kabukiza-single-act",
    src: "/images/guides/tokyo-kabukiza-single-act.jpg",
    title: "Inside Kabukiza",
    alt: "Rows of seated spectators face a striped stage curtain inside Tokyo's Kabukiza theatre, seen from an upper side balcony.",
    photographer: "urasimaru",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Kabukiza_in_2013_(11450043635).jpg",
    licenseName: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    rightsBasis: "documented_license",
    rightsCheckedOn: "2026-09-25",
    visualReview: {
      outcome: "approved",
      checkedOn: "2026-09-25",
      rationale:
        "The detailed interior establishes the room and its striped curtain without using copyrighted performance publicity or implying access to actors.",
    },
    depiction:
      "Historical interior photograph from 19 December 2013. It is not the view from the dedicated fourth-level single-act seats or a current performance. Resized and responsively cropped under the same CC BY-SA 2.0 license. No EA attendance or photographer endorsement is implied.",
  },
];
