import type { GuideMedia } from "./media";

const official = (
  guideId: string,
  file: string,
  title: string,
  alt: string,
  photographer: string,
  sourceUrl: string,
  rationale: string,
  depiction: string,
): GuideMedia => ({
  guideId,
  src: `/images/guides/${file}.jpg`,
  title,
  alt,
  photographer,
  sourceUrl,
  licenseName:
    "Official source photograph. Reuse rights not independently cleared",
  licenseUrl: sourceUrl,
  rightsBasis: "official_source",
  rightsCheckedOn: "2026-09-23",
  visualReview: { outcome: "approved", checkedOn: "2026-09-23", rationale },
  depiction: `${depiction} It does not prove EA attendance or guarantee future conditions. Reuse rights have not been independently cleared.`,
});

export const mediaBatch40: readonly GuideMedia[] = [
  official(
    "modena-giusti-acetaia",
    "modena-giusti-barrels",
    "Inside Giusti's acetaia",
    "A narrow passage runs between rows of wooden balsamic-vinegar barrels in Giusti's ageing rooms.",
    "Giusti. Individual photographer not named",
    "https://giusti.com/pages/casa-giusti",
    "Strong depth, textured barrels and restrained light make the actual ageing environment readable without relying on a bottle or marketing graphic.",
    "The producer's ageing room, not a guaranteed route, production stage or specific barrel used for a visitor tasting.",
  ),
  official(
    "tokyo-ninben-dashi-bar",
    "tokyo-ninben-dashi",
    "A cup at Nihonbashi Dashi Bar",
    "A staff member passes a white cup of dashi to a customer across Ninben's wooden counter.",
    "Ninben. Individual photographer not named",
    "https://www.ninben.co.jp/store/dashiba/",
    "The exchange of a small cup clearly identifies the visitor action. Warm counter detail survives both landscape cards and a larger detail crop.",
    "A serving photograph published by Ninben. The cup and counter illustrate the offer, not the exact future menu or staff.",
  ),
  official(
    "brussels-cantillon-brewery",
    "brussels-cantillon-coolship",
    "The brewery interior at Cantillon",
    "Exposed timber roof beams stand above a broad metal vessel in Cantillon's Brussels brewery.",
    "Brasserie Cantillon. Individual photographer not named",
    "https://www.cantillon.be/?lang=en",
    "Roof structure and the broad vessel make process and place visible. The wide composition is clear without beer-brand advertising or generic glasses.",
    "A Cantillon brewery interior. It does not establish that brewing is active on the day of an ordinary public visit.",
  ),
  official(
    "florence-il-papiro-marbling",
    "florence-il-papiro-colour",
    "Paper-marbling materials at Il Papiro",
    "A gloved hand works among jars of coloured pigment in Il Papiro's Florence paper-marbling workshop.",
    "Il Papiro. Individual photographer not named",
    "https://ilpapirofirenze.it/en/pages/workshop",
    "The documentary hand, worn jars and rich but natural pigment colour give the guide a precise working texture at card and detail scale.",
    "The programme's marbling workspace and materials, not a promise of a particular instructor or participant result.",
  ),
  official(
    "kyoto-shikata-kintsugi",
    "kyoto-shikata-repair",
    "Repair work at Shikata",
    "Hands hold a blue-and-white ceramic dish while a fine brush follows its repaired edge on a wooden bench.",
    "Shikata Kizo Urushi. Individual photographer not named",
    "https://kintsugi.shikataurushi.com/trial/",
    "Close working hands and a legible ceramic edge identify repair, not an ornamental gold effect. The source is 960 pixels wide and remains crisp at the intended detail column size.",
    "Repair work shown on Shikata's trial page. The object, metal finish and result are not promised to every participant.",
  ),
  official(
    "barcelona-handmade-espadrilles",
    "barcelona-espadrille-pair",
    "A finished espadrille pair",
    "A pair of black espadrilles with pale ties and contrasting stitched edges rests against a dark background.",
    "HANDMADE The Brand. Individual photographer not named",
    "https://espadrillesexperience.com/gallery/",
    "The uncluttered black-and-cream material study makes stitching and ties visible. Unlike the alternative programme poster, it contains no award sticker or promotional text.",
    "Finished shoes in the programme gallery, used as material context. Not an image of a current class or a guarantee of available colours, materials or results.",
  ),
  official(
    "dublin-na-fianna-gaelic-games",
    "dublin-gaelic-games-hurling",
    "Trying a hurling movement",
    "A participant in a burgundy shirt practises a hurling swing while other players watch from the grass.",
    "Experience Gaelic Games. Individual photographer not named",
    "https://experiencegaelicgames.com/",
    "The active swing and watching group make the introductory sporting action immediately understandable. The frame has enough detail for both desktop and mobile crops.",
    "An operator photograph of a hurling session. It does not identify the coach, venue or group assigned to a future Dublin booking.",
  ),
  official(
    "stockholm-tanto-guided-kayak",
    "stockholm-langholmen-kayaks",
    "Kayaks gathered on Stockholm water",
    "An overhead view shows a group of red kayaks gathered together beside a leafy Stockholm shoreline.",
    "Långholmen Kajak. Individual photographer not named",
    "https://langholmenkajak.se/en/pages/guidad-kajaktur-i-stockholm",
    "Actual paddlers, bright boats and green water give a strong compositional centre without a stock skyline. The high-resolution source remains clear in responsive crops.",
    "An operator group photograph illustrating kayaking. The pictured group is not the promised size or composition of the guided city tour.",
  ),
  official(
    "ljubljana-bananaway-sup",
    "ljubljana-guided-paddleboards",
    "Paddleboards on the Ljubljanica",
    "Five people stand on paddleboards on the Ljubljanica below the riverside buildings and trees of central Ljubljana.",
    "Bananaway. Individual photographer not named",
    "https://bananaway.eu/pages/sup-tour-ljubljana",
    "The river-level view unambiguously joins the practice to the city. The original has no embedded marketing text and the boards remain visible in a landscape crop.",
    "A posed group on the programme's river route. Conditions, instruction, group composition and water quality are not established by the photograph.",
  ),
  official(
    "lisbon-aguas-livres-crossing",
    "lisbon-aguas-livres-valley",
    "The Águas Livres aqueduct across the valley",
    "Stone arches of the Águas Livres aqueduct cross a green valley between Lisbon neighbourhoods.",
    "Turismo de Lisboa. Individual photographer not named",
    "https://www.visitlisboa.com/en/places/water-museum-aguas-livres-aqueduct",
    "A clear aerial overview gives the crossing its scale and city context. It is the named monument, without the museum banner or low-resolution text of the rejected alternative.",
    "An overview of the actual aqueduct. The aerial viewpoint is not accessible from the visitor walkway and the full historic network is not a public walking route.",
  ),
  official(
    "khwattu-san-tracking-tour",
    "khwattu-veld-vehicle",
    "The reserve landscape at !Khwa ttu",
    "An open vehicle sits among golden vegetation on a broad slope at !Khwa ttu in warm evening light.",
    "!Khwa ttu. Individual photographer not named",
    "https://www.khwattu.org/visit-and-explore/tours-and-trails/",
    "Warm natural light makes the veld's texture visible, with a real vehicle giving scale. It avoids staging a person as a cultural emblem or promising close wildlife contact.",
    "The centre's landscape and game-drive setting. It does not show tracking instruction, promise an evening departure or identify a future guide.",
  ),
  official(
    "naples-galleria-borbonica-standard",
    "naples-borbonica-wall",
    "Inside Galleria Borbonica",
    "A visitor stands beside a warmly lit textured wall with framed material inside Galleria Borbonica.",
    "Galleria Borbonica. Individual photographer not named",
    "https://www.galleriaborbonica.com/it/percorsi/standard",
    "The 1920-pixel official interior image has clear masonry texture and human scale. It replaces an attractive but only 400-pixel photograph that would blur on desktop.",
    "An official underground interior image published on the Standard route page. Particular objects and spaces may not appear on every departure.",
  ),
  official(
    "helsinki-loyly-public-sauna",
    "helsinki-loyly-shore",
    "Löyly on Helsinki's shoreline",
    "People pass the sculptural timber exterior of Löyly beside the Helsinki waterfront under a pale blue sky.",
    "Löyly. Individual photographer not named",
    "https://www.loylyhelsinki.fi/en",
    "The clean documentary frame identifies the building without an overlaid logo. Timber, sky and people make a composed architectural introduction rather than a generic spa picture.",
    "The actual Löyly exterior from its official film poster. It does not depict the public-sauna interior, swimming conditions or maintenance availability.",
  ),
  official(
    "budapest-szechenyi-daytime-bathing",
    "budapest-szechenyi-pools",
    "Outdoor bathing at Széchenyi",
    "Bathers gather in turquoise outdoor pools bordered by the yellow façades of Budapest's Széchenyi Bath.",
    "Budapest Spas / Széchenyi Bath. Individual photographer not named",
    "https://www.szechenyibath.hu/",
    "The real complex's colour and dense bathing activity provide a highly recognisable, detailed image. It is explicitly treated as an operating-history view, not live availability.",
    "The bath's outdoor-pool photograph. P1 is announced closed from 21 September to 2 October 2026 and P2 from 5 to 16 October. The image is not a live report of open pools or crowding.",
  ),
  official(
    "san-sebastian-la-perla-circuit",
    "san-sebastian-la-perla-pool",
    "The seawater circuit at La Perla",
    "Steps and stainless-steel rails descend into the symmetrical indoor pool circuit at La Perla in San Sebastián.",
    "La Perla. Individual photographer not named",
    "https://la-perla.net/en/thalassotherapy-gallery/",
    "The original gallery image gives the water and room geometry a clear calm centre. At 1513 pixels wide it replaces the unusable small preview from the ticket page.",
    "The actual circuit interior. An empty publicity photograph does not promise privacy, quietness or availability of every feature.",
  ),
  official(
    "lisbon-mesa-de-frades-fado",
    "lisbon-mesa-de-frades-room",
    "The tiled room at Mesa de Frades",
    "Dark wooden chairs and laid tables stand beside blue-and-white tile panels in Mesa de Frades' former-chapel dining room.",
    "Carol / Mesa de Frades",
    "https://mesadefrades.pt/",
    "The 2880-pixel room photograph preserves tile detail, table scale and warm light. It replaces the blank video poster and keeps the focus on the particular listening room.",
    "The venue's dining room before a performance. The source filename attributes the photographic set to Carol without a full name. No particular table, singer or view is guaranteed.",
  ),
  official(
    "buenos-aires-la-viruta-tango",
    "buenos-aires-la-viruta-floor",
    "The dance floor at La Viruta Tango AR",
    "Couples dance in a dimly lit room beneath La Viruta Tango AR's blue circular stage sign.",
    "La Viruta Tango AR. Individual photographer not named",
    "https://lavirutatangoar.com/",
    "The current 1400-pixel venue photograph shows an actual social floor, replacing a graphic studio-dancer cut-out. Low light is appropriate to the scene while the room and couples remain identifiable.",
    "An operating dance evening at the named venue, not the beginner class itself or a guarantee of a live band on every date.",
  ),
  official(
    "madrid-cardamomo-flamenco",
    "madrid-cardamomo-stage",
    "A performance at Cardamomo",
    "A flamenco dancer in a red dress performs on Cardamomo's small stage with musicians and a seated audience nearby.",
    "Cardamomo. Individual photographer not named",
    "https://cardamomo.com/en/",
    "The real stage, musicians and nearby audience make the performance relationship visible. The red dress supplies a natural focal point without added colour treatments or promotional overlays.",
    "A Cardamomo performance. It does not name or guarantee the dancer, musicians, seating or artistic programme for a future ticket.",
  ),
];
