import type { GuideMedia } from "./media";

const checkedOn = "2026-09-27";
const official = (
  guideId: string,
  title: string,
  alt: string,
  photographer: string,
  sourceUrl: string,
  rationale: string,
  depiction: string,
): GuideMedia => ({
  guideId,
  src: `/images/guides/${guideId}.jpg`,
  title,
  alt,
  photographer,
  sourceUrl,
  licenseName:
    "Official source photograph. Reuse rights not independently cleared",
  licenseUrl: sourceUrl,
  rightsBasis: "official_source",
  rightsCheckedOn: checkedOn,
  visualReview: { outcome: "approved", checkedOn, rationale },
  depiction: `${depiction} It does not prove EA attendance or guarantee future conditions. Reuse rights have not been independently cleared.`,
});
const licensed = (
  guideId: string,
  title: string,
  alt: string,
  photographer: string,
  sourceUrl: string,
  licenseName: string,
  licenseUrl: string,
  rationale: string,
  depiction: string,
): GuideMedia => ({
  guideId,
  src: `/images/guides/${guideId}.jpg`,
  title,
  alt,
  photographer,
  sourceUrl,
  licenseName,
  licenseUrl,
  rightsBasis: "documented_license",
  rightsCheckedOn: checkedOn,
  visualReview: { outcome: "approved", checkedOn, rationale },
  depiction: `${depiction} Resized and responsively cropped under the stated license. No EA attendance or photographer endorsement is implied.`,
});

export const mediaBatch43: readonly GuideMedia[] = [
  licensed(
    "parma-san-pier-damiani",
    "The age of a Parmigiano wheel",
    "Tall shelves of Parmigiano Reggiano wheels maturing in a working cheese cellar.",
    "Marie Thérèse Hébert & Jean Robert Thibault",
    "https://commons.wikimedia.org/wiki/File:Italie,_Lesignana_di_Modena,_Fromagerie_Quattro_Madonne,_productrice_de_Parmigiano_Reggiano,_%C3%89tape_4_de_la_fabrication_du_fromage_(50245500206).jpg",
    "CC BY-SA 2.0",
    "https://creativecommons.org/licenses/by-sa/2.0/",
    "The licensed documentary frame has a clear rhythm of wheels at human scale and shows maturation without borrowing the booked dairy's restricted imagery.",
    "The Quattro Madonne dairy near Modena, not San Pier Damiani or its booked tasting.",
  ),
  official(
    "bogota-catacion-plus",
    "Coffee by method",
    "A hand pours water over ground coffee during a Catación Pública brewing demonstration.",
    "Catación Pública. Individual photographer not named",
    "https://catacionpublica.co/products/experiencia-catacion-plus",
    "The exact operator's high-resolution image shows the physical extraction that the session asks visitors to compare.",
    "An operator photograph illustrating coffee preparation, not a guarantee of the exact method used in every session.",
  ),
  official(
    "sydney-bush-tucker",
    "Learning with a First Nations guide",
    "A First Nations guide introduces plants to visitors in Sydney's Royal Botanic Garden.",
    "Royal Botanic Garden Sydney. Individual photographer not named",
    "https://www.botanicgardens.org.au/whats-on/aboriginal-bush-tucker-tour",
    "The programme image shows the guide and garden in the same frame and keeps people, not just plants, at the centre.",
    "A photograph from the official tour page. The guide, group and samples may differ on a booked date.",
  ),
  official(
    "prague-pragl-hot-shop",
    "Inside Prague's glass hot shop",
    "A glassmaker works a glowing piece of glass before the furnace while visitors watch through a window at PRAGL in Prague.",
    "PRAGL / Prague Glass Experience. Individual photographer not named",
    "https://www.pragl.glass/glassworks",
    "The operator's sharply photographed glassmaker, hot material, furnace and onlookers show the real visitor setting without substituting a decorative object.",
    "An official studio photograph, not a promise that every visitor makes the pictured shape or watches this glassmaker.",
  ),
  licensed(
    "kanazawa-hakuichi-gold-leaf",
    "Gold leaf in Kanazawa",
    "A worker carefully lays a sheet of gold leaf on a pad at a Kanazawa gold workshop.",
    "Eckhard Pecher",
    "https://commons.wikimedia.org/wiki/File:Kanazawa_Gold_Factory.jpg",
    "CC BY 2.5",
    "https://creativecommons.org/licenses/by/2.5/",
    "The licensed photograph shows the delicacy of placing gold leaf at hand scale. The official tourism photographs explicitly prohibit republication, so none are reused.",
    "A Kanazawa gold workshop, not the Hakuichi visitor class or its finished object.",
  ),
  official(
    "hanoi-zo-calligraphy",
    "Brush on dó paper",
    "A participant moves a calligraphy brush across handmade paper at a Zó Project workshop.",
    "Zó Project. Individual photographer not named",
    "https://www.zoproject.com/service-page/calligraphy",
    "The participant's hand and brush reveal the moment of making in the exact workshop gallery.",
    "A Zó Project workshop photograph. Characters, instructor and location depend on the booked session.",
  ),
  official(
    "copenhagen-copenhill-ski",
    "Skiing on CopenHill",
    "A skier turns on CopenHill's green artificial slope above Copenhagen.",
    "CopenHill. Individual photographer not named",
    "https://www.copenhill.dk/en/activities/ski-snowboard",
    "The exact slope and city context make this unexpected rooftop movement legible immediately.",
    "An operator photograph of the synthetic slope, not a promise of weather, an instructor or an open run.",
  ),
  official(
    "madeira-balcoes-levada",
    "Along the Balcões path",
    "A walker follows the path through dense green laurel forest on Madeira's Balcões route.",
    "Francisco Correia / Visit Madeira",
    "https://www.visitmadeira.com/en/what-to-do/nature-seekers/activities/hiking/pr-11-vereda-dos-balcoes/",
    "The official route photograph puts the walker inside the forest rather than substituting an unrelated island overlook.",
    "An official PR11 route photograph. Trail condition, light and weather may differ.",
  ),
  licensed(
    "seville-guided-river-kayak",
    "Seville at paddle height",
    "Small kayaks move along the Guadalquivir below Seville's riverside buildings.",
    "Daderot",
    "https://commons.wikimedia.org/wiki/File:Kayaks_on_the_Guadalquivir,_Sevilla,_Spain_-_DSC07671.JPG",
    "CC0",
    "https://creativecommons.org/publicdomain/zero/1.0/",
    "The documentary frame is genuinely on the Seville river and shows the scale of a kayak against the city. It is less close-up than ideal but avoids unlicensed reseller imagery.",
    "Independent river photograph, not a photograph of Kayak Sevilla's guided group or route.",
  ),
  official(
    "barcelona-sant-pau",
    "Sant Pau's connected courtyards",
    "Visitors walk beside the ornate pavilions and planted courtyard of Barcelona's Sant Pau complex.",
    "Recinte Modernista de Sant Pau. Individual photographer not named",
    "https://santpaubarcelona.org/visita/visita-lliure/",
    "The venue's detailed photograph connects architecture, human scale and open space for the self-guided visit.",
    "The Sant Pau visitor complex, not an assurance that every room or pavilion will be open.",
  ),
  licensed(
    "porto-casa-da-musica-tour",
    "Looking into Casa da Música",
    "Daylight crosses the glass-lined Sala Suggia passage inside Porto's Casa da Música.",
    "Acfmagalhaes",
    "https://commons.wikimedia.org/wiki/File:Interior_da_Casa_da_M%C3%BAsica.jpg",
    "CC BY-SA 4.0",
    "https://creativecommons.org/licenses/by-sa/4.0/",
    "A recent, licensed architectural view makes the building's circulation, light and relationship to the city more compelling than a generic facade.",
    "A Casa da Música interior, not a guarantee that every guided tour enters the pictured Sala Suggia passage.",
  ),
  licensed(
    "london-soane-house",
    "Inside Soane's crowded house",
    "Sculptures and architectural fragments line a narrow, sunlit stairwell inside Sir John Soane's Museum.",
    "Simon Burchell",
    "https://commons.wikimedia.org/wiki/File:Sir_John_Soane%27s_Museum,_Lincoln%27s_Inn_Fields,_London_07.jpg",
    "CC BY-SA 4.0",
    "https://creativecommons.org/licenses/by-sa/4.0/",
    "The dense stairwell gives a truthful glimpse of the house's spatial surprises and collection.",
    "A museum interior from a previous visit, not proof of access to restricted rooms today.",
  ),
  official(
    "hoi-an-quiet-teahouse",
    "Tea at Reaching Out",
    "A ceramic cup, teapot and small dishes sit on a quiet table at Reaching Out Teahouse in Hoi An.",
    "Reaching Out. Individual photographer not named",
    "https://www.reachingoutvietnam.com/teahouse/the-teahouse/",
    "The teahouse's own considered photograph supports the quiet, deliberate service rather than generic Vietnamese tea imagery.",
    "An operator image of tea service. Menu, table and sensory experience may differ.",
  ),
  official(
    "sydney-maccallum-pool",
    "A harbour-length swim",
    "Maccallum Pool stretches along Sydney Harbour at Cremorne Point in warm evening light.",
    "Destination NSW / ATDW. Individual photographer not named",
    "https://www.sydney.com/destinations/sydney/sydney-north/mosman/attractions/maccallum-pool",
    "The state tourism image clearly locates this unusual public saltwater pool at the harbour edge.",
    "A tourism photograph of Maccallum Pool, not evidence of current water quality, cleaning or swimming conditions.",
  ),
  licensed(
    "marrakech-jardin-secret",
    "Water and shade at Le Jardin Secret",
    "A green water channel crosses Le Jardin Secret's planted courtyard toward a shaded pavilion in Marrakech.",
    "muffinn",
    "https://commons.wikimedia.org/wiki/File:Morocco_-_Marrakech_-_Le_Jardin_Secret_(49133982557).jpg",
    "CC BY 2.0",
    "https://creativecommons.org/licenses/by/2.0/",
    "The licensed garden photograph makes the water architecture and respite from the medina visible together.",
    "A previous view of Le Jardin Secret, not a promise of identical planting, access or light.",
  ),
  official(
    "valencia-water-tribunal",
    "The water court in public",
    "Tribunal de les Aigües members sit outside Valencia's cathedral during a public water hearing.",
    "Tribunal de les Aigües de la Vega de València. Individual photographer not named",
    "https://tribunaldelasaguas.org/visitas-al-tribunal/",
    "The Tribunal's own current image shows the actual hearing arrangement and its public setting.",
    "An official tribunal photograph. A particular hearing or dispute is never guaranteed.",
  ),
  licensed(
    "paris-bal-blomet-jazz",
    "The Bal Blomet room",
    "An empty performance stage glows pink beneath the Bal Blomet name in Paris.",
    "Zythème",
    "https://commons.wikimedia.org/wiki/File:Bal_Blomet.jpg",
    "CC0",
    "https://creativecommons.org/publicdomain/zero/1.0/",
    "The licensed venue-specific stage sets expectations for a small live-music room without borrowing an unidentified concert photograph.",
    "The room without performers, not the advertised trio or a promise of a particular show.",
  ),
  licensed(
    "singapore-esplanade-concourse",
    "A performance at Esplanade",
    "A singer performs for an audience at Esplanade's Concourse in Singapore.",
    "Choo Yut Shing",
    "https://commons.wikimedia.org/wiki/File:Musical_Performance_-_Flickr_-_chooyutshing.jpg",
    "CC BY 2.0",
    "https://creativecommons.org/licenses/by/2.0/",
    "The licensed documentary frame shows the scale and shared nature of a public Concourse performance.",
    "An earlier performance, not the currently scheduled free set or its performers.",
  ),
];
