import type { GuideMedia } from "./media";

const official = (
  guideId: string,
  file: string,
  title: string,
  alt: string,
  photographer: string,
  sourceUrl: string,
  rationale: string,
  depiction: string,
): GuideMedia => ({
  guideId,
  src: `/images/guides/${file}.jpg`,
  title,
  alt,
  photographer,
  sourceUrl,
  licenseName:
    "Official source photograph. Reuse rights not independently cleared",
  licenseUrl: sourceUrl,
  rightsBasis: "official_source",
  rightsCheckedOn: "2026-09-24",
  visualReview: { outcome: "approved", checkedOn: "2026-09-24", rationale },
  depiction: `${depiction} It does not prove EA attendance or guarantee future conditions. Reuse rights have not been independently cleared.`,
});

export const mediaBatch41: readonly GuideMedia[] = [
  official(
    "melbourne-qvm-foodie-tour",
    "melbourne-qvm-counter",
    "Across a Queen Victoria Market counter",
    "A market trader leans behind a glass counter surrounded by bread, pastries and labelled jars at Queen Victoria Market.",
    "Queen Victoria Market. Individual photographer not named",
    "https://qvm.com.au/tours/",
    "The real trader and dense counter make place and exchange legible. The clean 760-pixel source works at the bounded detail-column size without promotional overlays.",
    "A market trader photograph published for the food tour. The stall, staff member and products are illustrative, not guaranteed tour stops or tastings.",
  ),
  official(
    "taipei-wangtea-lab",
    "taipei-wangtea-draft",
    "Tea at Wangtea Lab",
    "Six small glasses of different tea drinks stand on a wooden ledge against a pale wall at Wangtea Lab.",
    "Wangtea Lab. Individual photographer not named",
    "https://www.wangtealab.com/",
    "Natural warm colour, clear glass and a quiet background make the tea comparison readable. The high-resolution image has no embedded labels or stock-place substitution.",
    "The bar's menu photograph, not an included six-glass tasting flight or proof that all pictured drinks are non-alcoholic.",
  ),
  official(
    "mexico-city-mucho-cacao",
    "mexico-city-mucho-room",
    "Inside MUCHO",
    "A long wooden table with cacao-processing tools stands beneath colourful displays inside Mexico City's chocolate museum.",
    "Secretaría de Turismo de la Ciudad de México. Individual photographer not named",
    "https://mexicocity.cdmx.gob.mx/venues/mundo-chocolate-mucho/?lang=en",
    "The museum's actual room connects material tools with an inviting, colourful interior. It is specific to MUCHO rather than a generic chocolate close-up.",
    "An interior published by Mexico City tourism. It does not promise a hands-on workshop, available equipment or a free tasting.",
  ),
  official(
    "lisbon-puraceramica-handbuilding",
    "lisbon-handbuilt-clay",
    "Handbuilt forms at PURACERÂMICA",
    "Small handmade clay cups and bowls rest together on a studio work surface.",
    "PURACERÂMICA. Individual photographer not named",
    "https://www.puraceramica.pt/en/handbuilding-workshop.html",
    "The source's high-resolution material study makes imperfect rims and handbuilt form tangible without substituting a wheel-throwing photograph.",
    "Clay forms shown on the handbuilding course page. They are examples, not guaranteed participant results or same-day fired objects.",
  ),
  official(
    "tokyo-sokichi-kiriko",
    "tokyo-sokichi-cut-glass",
    "Cutting a glass at Sokichi",
    "Hands hold a purple glass against a cutting wheel in Sokichi's workshop.",
    "Sokichi. Individual photographer not named",
    "https://en.sokichi-workshop.com/flow",
    "Close working hands and the contact between glass and wheel identify the exact process. The detailed original remains crisp in both responsive layouts.",
    "A workshop process photograph. The coloured glass is not the included clear-glass base option and may cost extra.",
  ),
  official(
    "bangkok-sompong-curry",
    "bangkok-sompong-kitchen",
    "Cooking at Sompong",
    "Participants in blue aprons cook at individual wok stations in Sompong's timber-lined Bangkok kitchen.",
    "Sompong Thai Cooking School. Individual photographer not named",
    "https://sompongthaicookingschool.com/home",
    "The real kitchen, active woks and individual stations show the visitor's role clearly. Warm natural materials support the image without added slogans.",
    "An operator photograph of a cooking class. It does not identify the exact morning menu, teacher, group size or future participants.",
  ),
  official(
    "sydney-manly-adult-surf",
    "sydney-manly-first-surf",
    "A Manly Surf School session",
    "Participants in yellow rash vests smile beside soft surfboards in shallow water during a Manly Surf School session.",
    "Manly Surf School. Individual photographer not named",
    "https://manlysurfschool.com/adult-surf-lessons-sydney/",
    "A clean single documentary frame replaces the low-resolution collage and watermarked advanced-wave alternatives. Boards, learners and water make the introductory activity unmistakable.",
    "A promotional participant photograph from the school's adult-lesson media. It does not guarantee standing, wave conditions or a particular instructor.",
  ),
  official(
    "bangkok-co-classical-cycle",
    "bangkok-chinatown-bicycle",
    "A bicycle in Bangkok's market streets",
    "A cyclist and a yellow bicycle move through a narrow Bangkok market street between stalls and pedestrians.",
    "Co van Kessel. Individual photographer not named",
    "https://www.covankessel.com/bangkok/co-classical-3-hour-bicycle-tour",
    "The street-level frame makes the human scale and narrow route visible. It connects cycling to an inhabited place rather than an empty skyline.",
    "An operator photograph of the route environment. Streets, crowds and stops may change and residents are not part of a staged visitor programme.",
  ),
  official(
    "buenos-aires-south-circuit",
    "buenos-aires-plaza-cycle",
    "Cycling across Plaza de Mayo",
    "Helmeted cyclists with orange bicycle baskets cross Plaza de Mayo with the Casa Rosada behind them.",
    "BA Bikes. Individual photographer not named",
    "https://buenosairesbiketours.com/book-now/",
    "The original 1600-pixel frame replaces the 400-pixel thumbnail. Moving riders and the recognisable civic square give both activity and place a clear role.",
    "The South Circuit's published route photograph. Group composition, traffic and exact stops are not guaranteed.",
  ),
  official(
    "singapore-ura-city-gallery",
    "singapore-city-model",
    "Singapore's city model",
    "Visitors stand around a large detailed model of central Singapore in the Singapore City Gallery.",
    "Urban Redevelopment Authority",
    "https://www.ura.gov.sg/get-involved/singapore-city-gallery/",
    "The model and visitors establish the relationship of scale immediately. The 900-pixel source is suitable for the bounded detail column and avoids generic skyline substitution.",
    "URA's exhibition photograph. It is not an image of the full-scale city or proof of a particular current display configuration.",
  ),
  official(
    "cape-town-kirstenbosch-walk",
    "kirstenbosch-canopy-path",
    "Kirstenbosch's tree canopy walkway",
    "A curved timber walkway with metal mesh rails passes through sunlit trees at Kirstenbosch.",
    "Alice Notten / SANBI",
    "https://www.sanbi.org/wp-content/uploads/2026/08/KIRSTENBOSCH-tree-canopy-walkway-Alice-Notten-scaled.jpg",
    "The high-resolution curve through real foliage offers depth, natural light and a clear sense of walking. It replaces an oversaturated flower close-up and an unusably narrow banner.",
    "Alice Notten's garden walkway photograph, credited in SANBI's media record. This is garden context, not a promise that the volunteer walk uses this section.",
  ),
  {
    guideId: "taipei-ri-xing-type",
    src: "/images/guides/taipei-ri-xing-type.jpg",
    title: "Ri Xing Type Foundry, interior",
    alt: "Closely packed rows of metal printing type stand on labelled shelves inside Ri Xing Type Foundry in Taipei.",
    photographer: "Johan Jönsson (Julle)",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Ri_Xing_Type_Foundry_01.jpg",
    licenseName: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    rightsBasis: "documented_license",
    rightsCheckedOn: "2026-09-24",
    visualReview: {
      outcome: "approved",
      checkedOn: "2026-09-24",
      rationale:
        "The exact foundry's shelves show type as physical inventory. Fine detail, restrained colour and repetition remain legible without a collage or staged printing lesson.",
    },
    depiction:
      "Ri Xing's interior photographed on 11 August 2023. It does not establish current stock or visitor handling access. Resized and cropped responsively for web delivery, available under CC BY-SA 4.0. Not an EA visit.",
  },
  official(
    "tokyo-haginoyu-sento",
    "tokyo-haginoyu-washing",
    "Hagino-yu's washing area",
    "Rows of green washing stools and shower stations line a bright tiled room at Hagino-yu.",
    "Hagino-yu. Individual photographer not named",
    "https://haginoyu.jp/introduction/",
    "The empty, evenly framed washing room shows the bathhouse sequence without intruding on bathers. Material and colour are specific to the actual venue.",
    "The bathhouse's official washing-area photograph. It does not show every bath, current occupancy or an independent inspection.",
  ),
  {
    guideId: "london-parliament-hill-lido",
    src: "/images/guides/london-parliament-hill-pool.jpg",
    title: "Parliament Hill Lido",
    alt: "Blue water fills the outdoor Parliament Hill Lido, with swimmers, low pool buildings and trees along the far side.",
    photographer: "Tom Page",
    sourceUrl:
      "https://commons.wikimedia.org/wiki/File:Parliament_Hill_Lido_(7321222708).jpg",
    licenseName: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    rightsBasis: "documented_license",
    rightsCheckedOn: "2026-09-24",
    visualReview: {
      outcome: "approved",
      checkedOn: "2026-09-24",
      rationale:
        "The water-level view identifies the real outdoor pool and its generous scale. It avoids promotional events, jumping shots and a warning-sign-led composition.",
    },
    depiction:
      "Parliament Hill Lido photographed on 2 June 2012. Historical place context, not evidence of current temperature, facilities, weather or access. Resized and cropped responsively, available under CC BY-SA 2.0. Not an EA visit.",
  },
  official(
    "rotorua-pavilion-pools",
    "rotorua-pavilion-steam",
    "Pavilion Pools beside Lake Rotorua",
    "Bathers rest in steaming outdoor Pavilion Pools with Lake Rotorua beyond the pool edge.",
    "Polynesian Spa. Individual photographer not named",
    "https://www.polynesianspa.co.nz/bathing/pavilion-pools/",
    "The actual Pavilion pool setting combines water, steam and lake depth without a generic spa interior. The source is sufficiently detailed for mobile and desktop crops.",
    "The provider's Pavilion Pools photograph. It does not promise the same weather, temperature, occupancy or private access.",
  ),
  official(
    "bangkok-sala-chalermkrung",
    "bangkok-khon-gesture",
    "A khon scene at Sala Chalermkrung",
    "Two costumed performers, one wearing a white mask, exchange gestures on a blue-lit stage at Sala Chalermkrung.",
    "Sala Chalermkrung. Individual photographer not named",
    "https://salachalermkrung.com/?c=news&cid=90&m=detail",
    "A clear exchange between two figures makes gesture and character visible. The real programme image avoids confusing a regional group dance with the khon portion.",
    "A scene published with the theatre's visitor programme. The programme mixes performance forms and does not guarantee these performers, costumes or this exact staging.",
  ),
  official(
    "new-orleans-preservation-hall",
    "new-orleans-preservation-ensemble",
    "Preservation Hall ensemble",
    "Musicians with brass, clarinet and drums gather in Preservation Hall's warmly lit New Orleans room.",
    "Camille Lenain / Preservation Hall",
    "https://www.preservationhall.com/",
    "The credited ensemble image makes the close room and acoustic instruments central. Strong tonal detail and an uncluttered frame work at both card and detail scale.",
    "Camille Lenain's official ensemble portrait, credited in the published image filename. It is not a photograph of a specified future show or a promised line-up.",
  ),
  official(
    "seoul-saturday-gugak",
    "seoul-gugak-dance",
    "Dance at the National Gugak Center",
    "Performers in blue and red traditional garments with white sleeves move across a wooden stage at the National Gugak Center.",
    "Korea Tourism Organization. Individual photographer not named",
    "https://english.visitkorea.or.kr/svc/sp/kperformance/contentsView.do?dataSetId=92&menuSn=894&vcontsId=104077",
    "The restrained stage photograph makes ensemble movement legible without a promotional poster. The 940-pixel original is suitable for the bounded detail-column layout.",
    "A programme image from Visit Korea's Saturday Gugak listing. Repertoire changes and the pictured dance is not promised on every date.",
  ),
];
